[tool.poetry]
name = "airflow-tutorial"
version = "0.1"
description = ""
authors = ["Luciano Borba"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
apache-airflow = "^2.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
